name = "stylo"
pages_build_output_dir = "./dist"
compatibility_date = "2026-03-30"
compatibility_flags = ["nodejs_compat"]

[vars]
SUPABASE_URL = "https://icdgsglzrcculwymgluu.supabase.co"

[[d1_databases]]
binding = "DB"
database_name = "stylo"
database_id = "b7898b3b-2b6a-4173-a3f0-af4a84eefe7c"

[[durable_objects.bindings]]
name = "PROJECT_REALTIME"
class_name = "ProjectRealtimeRoom"
script_name = "stylo-project-realtime"
