import type {
  NodeFlowHandle,
  StyloAgentBridge,
} from "../bridge/styloBridge";
import { getNodeFlowRef } from "../runtime/nodeFlowRefs";
import { assertGenericWriteAllowedForNode, findNodeByIdOrRef } from "./foundationAccess";

export const OPERATE_NODEFLOW_ENTITIES = ["node", "link"] as const;
export const OPERATE_NODEFLOW_ACTIONS = ["create", "update", "move", "connect"] as const;
export const OPERATE_NODEFLOW_TARGETS = ["nodeflow:node", "nodeflow:link"] as const;
export const OPERATE_NODEFLOW_NODE_KINDS = ["script", "archive", "text", "image", "audio", "video", "pdf"] as const;

type OperateEntity = (typeof OPERATE_NODEFLOW_ENTITIES)[number];
type OperateAction = (typeof OPERATE_NODEFLOW_ACTIONS)[number];
type OperateNodeKind = (typeof OPERATE_NODEFLOW_NODE_KINDS)[number];

const slugifyRefToken = (value: string, fallback: string) =>
  value
    .trim()
    .toLowerCase()
    .replace(/[\s_/]+/g, "_")
    .replace(/[^\w\u4e00-\u9fa5-]+/g, "")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "") || fallback;

const operateProjectResourceParameters = {
  type: "object",
  properties: {
    entity: {
      type: "string",
      enum: [...OPERATE_NODEFLOW_ENTITIES],
      description: "Which Flow graph entity to operate on.",
    },
    action: {
      type: "string",
      enum: [...OPERATE_NODEFLOW_ACTIONS],
      description: "Atomic Flow graph action. Nodes support create, update, move. Links support connect. Destructive remove/unlink actions are not directly exposed to the agent.",
    },
    link_role: {
      type: "string",
      enum: ["connection", "reference"],
      description: "Whether the Flow graph link is a visible canvas connection or an internal reference relation.",
    },
    node_kind: {
      type: "string",
      description: "Flow graph node kind to create. Only supports basic nodes: script, archive, text, image, audio, video, pdf. Folder nodes are generated by foundation operations.",
    },
    node_id: {
      type: "string",
      description: "Existing Flow graph node id.",
    },
    node_ref: {
      type: "string",
      description: "Existing Flow graph node ref.",
    },
    link_id: {
      type: "string",
      description: "Existing Flow graph link id. Destructive unlink is not directly exposed to the agent.",
    },
    title: {
      type: "string",
      description: "Optional node title.",
    },
    text: {
      type: "string",
      description: "Text content for text nodes or text patches.",
    },
    content: {
      type: "string",
      description: "Markdown/Fountain content for archive, script, or text nodes.",
    },
    image_url: {
      type: "string",
      description: "Image URL for image nodes.",
    },
    audio_url: {
      type: "string",
      description: "Audio URL for audio nodes.",
    },
    video_url: {
      type: "string",
      description: "Video URL for video nodes.",
    },
    pdf_url: {
      type: "string",
      description: "PDF URL for PDF input nodes.",
    },
    filename: {
      type: "string",
      description: "Optional file label for media nodes.",
    },
    mime_type: {
      type: "string",
      description: "Optional MIME type for audio, video, or PDF nodes.",
    },
    patch: {
      type: "object",
      description: "Structured Flow graph node patch for update.",
      additionalProperties: true,
    },
    x: {
      type: "number",
      description: "Target canvas x position for create or move.",
    },
    y: {
      type: "number",
      description: "Target canvas y position for create or move.",
    },
    parent_id: {
      type: "string",
      description: "Optional parent node id when creating a node.",
    },
    scene_id: {
      type: "string",
      description: "Optional scene id for node patching.",
    },
    source_ref: {
      type: "string",
      description: "Source node ref when connecting Flow graph links.",
    },
    target_ref: {
      type: "string",
      description: "Target node ref when connecting Flow graph links.",
    },
    source_node_id: {
      type: "string",
      description: "Source node id when connecting Flow graph links.",
    },
    target_node_id: {
      type: "string",
      description: "Target node id when connecting Flow graph links.",
    },
    source_handle: {
      type: "string",
      description: "Optional explicit source handle for connection links.",
    },
    target_handle: {
      type: "string",
      description: "Optional explicit target handle for connection links.",
    },
  },
  additionalProperties: false,
  required: ["entity", "action"],
} as const;

const normalizeString = (value: unknown) => (typeof value === "string" ? value.trim() : "");

const normalizeNodeKind = (rawNodeKind: unknown): OperateNodeKind | "" => {
  const value = normalizeString(rawNodeKind);
  if (value === "script_page" || value === "script_node" || value === "script_document") return "script";
  if (value === "archive_document" || value === "archive_node" || value === "document" || value === "md_text") return "archive";
  if (value === "image_input") return "image";
  if (value === "audio_input") return "audio";
  if (value === "video_input") return "video";
  if (value === "pdf_input" || value === "pdf_document") return "pdf";
  if ((OPERATE_NODEFLOW_NODE_KINDS as readonly string[]).includes(value)) {
    return value as OperateNodeKind;
  }
  return "";
};

type ParsedArgs =
  | {
      entity: "node";
      action: "create";
      nodeKind: OperateNodeKind;
      nodeRef?: string;
      parentId?: string;
      title?: string;
      text?: string;
      content?: string;
      imageUrl?: string;
      audioUrl?: string;
      videoUrl?: string;
      pdfUrl?: string;
      filename?: string;
      mimeType?: string;
      x?: number;
      y?: number;
    }
  | {
      entity: "node";
      action: "update";
      nodeId?: string;
      nodeRef?: string;
      patch: Record<string, unknown>;
    }
  | {
      entity: "node";
      action: "move";
      nodeId?: string;
      nodeRef?: string;
      x: number;
      y: number;
    }
  | {
      entity: "link";
      action: "connect";
      linkKind: "canvas" | "graph";
      sourceRef?: string;
      targetRef?: string;
      sourceNodeId?: string;
      targetNodeId?: string;
      sourceHandle?: string;
      targetHandle?: string;
    };

const buildNodePatch = (raw: Record<string, unknown>) => {
  const explicitPatch =
    raw.patch && typeof raw.patch === "object" && !Array.isArray(raw.patch)
      ? { ...(raw.patch as Record<string, unknown>) }
      : {};

  const title = normalizeString(raw.title);
  const text = normalizeString(raw.text);
  const content = normalizeString(raw.content);
  const imageUrl = normalizeString(raw.image_url ?? raw.imageUrl);
  const audioUrl = normalizeString(raw.audio_url ?? raw.audioUrl);
  const videoUrl = normalizeString(raw.video_url ?? raw.videoUrl);
  const pdfUrl = normalizeString(raw.pdf_url ?? raw.pdfUrl);
  const filename = normalizeString(raw.filename);
  const mimeType = normalizeString(raw.mime_type ?? raw.mimeType);
  const sceneId = normalizeString(raw.scene_id ?? raw.sceneId);

  if (title) explicitPatch.title = title;
  if (text) explicitPatch.text = text;
  if (content) {
    explicitPatch.content = content;
    if (!text) explicitPatch.text = content;
  }
  if (imageUrl) explicitPatch.image = imageUrl;
  if (audioUrl) explicitPatch.audio = audioUrl;
  if (videoUrl) explicitPatch.video = videoUrl;
  if (pdfUrl) explicitPatch.pdf = pdfUrl;
  if (filename) explicitPatch.filename = filename;
  if (mimeType) explicitPatch.mimeType = mimeType;
  if (sceneId) explicitPatch.sceneId = sceneId;
  return explicitPatch;
};

const parseArgs = (input: unknown): ParsedArgs => {
  if (!input || typeof input !== "object" || Array.isArray(input)) {
    throw new Error("operate_project_resource 需要对象参数。");
  }
  const raw = input as Record<string, unknown>;
  const entity = normalizeString(raw.entity) as OperateEntity;
  const action = normalizeString(raw.action) as OperateAction;

  if (!(OPERATE_NODEFLOW_ENTITIES as readonly string[]).includes(entity)) {
    throw new Error(`operate_project_resource 不支持 entity=${normalizeString(raw.entity)}`);
  }
  if (!(OPERATE_NODEFLOW_ACTIONS as readonly string[]).includes(action)) {
    throw new Error(`operate_project_resource 不支持 action=${normalizeString(raw.action)}`);
  }

  if (entity === "node") {
    const nodeId = normalizeString(raw.node_id ?? raw.nodeId) || undefined;
    const nodeRef = normalizeString(raw.node_ref ?? raw.nodeRef) || undefined;

    if (action === "create") {
      const nodeKind = normalizeNodeKind(raw.node_kind ?? raw.nodeKind);
      const parentId = normalizeString(raw.parent_id ?? raw.parentId) || undefined;
      const title = normalizeString(raw.title) || undefined;
      const text = normalizeString(raw.text) || undefined;
      const content = typeof raw.content === "string" ? raw.content : undefined;
      const imageUrl = normalizeString(raw.image_url ?? raw.imageUrl) || undefined;
      const audioUrl = normalizeString(raw.audio_url ?? raw.audioUrl) || undefined;
      const videoUrl = normalizeString(raw.video_url ?? raw.videoUrl) || undefined;
      const pdfUrl = normalizeString(raw.pdf_url ?? raw.pdfUrl) || undefined;
      const filename = normalizeString(raw.filename) || undefined;
      const mimeType = normalizeString(raw.mime_type ?? raw.mimeType) || undefined;
      const x = typeof raw.x === "number" ? raw.x : undefined;
      const y = typeof raw.y === "number" ? raw.y : undefined;

      if (!nodeKind) {
        throw new Error("创建 Flow 节点需要合法的 node_kind。");
      }
      if (nodeKind === "text" && !(text || content?.trim())) {
        throw new Error("创建 text 节点时需要 text。");
      }
      return {
        entity: "node",
        action: "create",
        nodeKind,
        nodeRef,
        parentId,
        title,
        text,
        content,
        imageUrl,
        audioUrl,
        videoUrl,
        pdfUrl,
        filename,
        mimeType,
        x,
        y,
      };
    }

    if (!nodeId && !nodeRef) {
      throw new Error(`Flow 节点 ${action} 需要 node_id 或 node_ref。`);
    }

    if (action === "update") {
      const patch = buildNodePatch(raw);
      if (!Object.keys(patch).length) {
        throw new Error("更新 Flow 节点需要 patch 或可映射到 patch 的字段。");
      }
      return {
        entity: "node",
        action: "update",
        nodeId,
        nodeRef,
        patch,
      };
    }

    if (action === "move") {
      const x = typeof raw.x === "number" ? raw.x : undefined;
      const y = typeof raw.y === "number" ? raw.y : undefined;
      if (typeof x !== "number" || typeof y !== "number") {
        throw new Error("移动 Flow 节点需要明确的 x 和 y。");
      }
      return {
        entity: "node",
        action: "move",
        nodeId,
        nodeRef,
        x,
        y,
      };
    }

    throw new Error(`Flow 节点当前不支持 action=${action}`);
  }

  if (action === "connect") {
    const linkRole = (normalizeString(raw.link_role ?? raw.linkRole) || "connection") as
      | "connection"
      | "reference";
    const sourceRef = normalizeString(raw.source_ref ?? raw.sourceRef) || undefined;
    const targetRef = normalizeString(raw.target_ref ?? raw.targetRef) || undefined;
    const sourceNodeId = normalizeString(raw.source_node_id ?? raw.sourceNodeId) || undefined;
    const targetNodeId = normalizeString(raw.target_node_id ?? raw.targetNodeId) || undefined;
    const sourceHandle = normalizeString(raw.source_handle ?? raw.sourceHandle) || undefined;
    const targetHandle = normalizeString(raw.target_handle ?? raw.targetHandle) || undefined;

    if ((!sourceRef && !sourceNodeId) || (!targetRef && !targetNodeId)) {
      throw new Error("连接 Flow 连线时需要为两端分别提供 ref 或 node_id。");
    }
    if ((sourceRef || sourceNodeId) === (targetRef || targetNodeId)) {
      throw new Error("Flow 连线不能连接同一个节点到自己。");
    }

    return {
      entity: "link",
      action: "connect",
      linkKind: linkRole === "reference" ? "graph" : "canvas",
      sourceRef,
      targetRef,
      sourceNodeId,
      targetNodeId,
      sourceHandle,
      targetHandle,
    };
  }

  throw new Error(`Flow 连线当前不支持 action=${action}`);
};

const resolveNodeType = (nodeKind: OperateNodeKind) => {
  if (nodeKind === "script") return "scriptPage" as const;
  if (nodeKind === "archive") return "mdText" as const;
  if (nodeKind === "image") return "imageInput" as const;
  if (nodeKind === "audio") return "audioInput" as const;
  if (nodeKind === "video") return "videoInput" as const;
  if (nodeKind === "pdf") return "pdfInput" as const;
  return "text" as const;
};

const defaultTitle = (args: Extract<ParsedArgs, { entity: "node"; action: "create" }>) => {
  if (args.title) return args.title;
  if (args.nodeKind === "script") return "剧本文档";
  if (args.nodeKind === "archive") return "档案文档";
  if (args.nodeKind === "image") return args.filename || "图片节点";
  if (args.nodeKind === "audio") return args.filename || "音频节点";
  if (args.nodeKind === "video") return args.filename || "视频节点";
  if (args.nodeKind === "pdf") return args.filename || "PDF 节点";
  return (args.text || args.content || "").slice(0, 24) || "文本节点";
};

const defaultNodeRef = (args: Extract<ParsedArgs, { entity: "node"; action: "create" }>) => {
  if (args.nodeRef) return args.nodeRef;
  if (args.nodeKind === "script") return `script_${slugifyRefToken(args.title || Date.now().toString(), "document")}`;
  if (args.nodeKind === "archive") return `archive_${slugifyRefToken(args.title || Date.now().toString(), "document")}`;
  if (args.nodeKind === "image") return `image_${slugifyRefToken(args.filename || args.title || Date.now().toString(), "asset")}`;
  if (args.nodeKind === "audio") return `audio_${slugifyRefToken(args.filename || args.title || Date.now().toString(), "asset")}`;
  if (args.nodeKind === "video") return `video_${slugifyRefToken(args.filename || args.title || Date.now().toString(), "asset")}`;
  if (args.nodeKind === "pdf") return `pdf_${slugifyRefToken(args.filename || args.title || Date.now().toString(), "asset")}`;
  return `text_${slugifyRefToken(args.title || args.text || args.content || Date.now().toString(), "note")}`;
};

const defaultDocumentId = (args: Extract<ParsedArgs, { entity: "node"; action: "create" }>) =>
  `${slugifyRefToken(args.nodeRef || args.title || "document", "document")}-${Date.now().toString(36)}`;

const resolveNodeFlowRefForGraph = (
  workflow: ReturnType<StyloAgentBridge["getNodeFlowSnapshot"]>,
  nodeId?: string,
  nodeRef?: string
) => {
  if (nodeRef) return nodeRef;
  if (nodeId) {
    const workflowNode = workflow.nodes.find((node) => node.id === nodeId);
    if (workflowNode) return getNodeFlowRef(workflowNode) || workflowNode.id;
  }
  return undefined;
};

export const operateProjectResourceToolDef = {
  name: "operate_project_resource",
  description:
    "Operate the visible Flow graph by performing atomic node or link actions. The internal layer key is nodeflow, but this is not a separate product mode.",
  parameters: operateProjectResourceParameters,
  execute: (input: unknown, bridge: StyloAgentBridge) => {
    const args = parseArgs(input);
    const workflow = bridge.getNodeFlowSnapshot();
    const expectedRevision = workflow.revision;

    if (args.entity === "node" && args.action === "create") {
      if (args.parentId) {
        assertGenericWriteAllowedForNode(
          findNodeByIdOrRef(workflow, { nodeId: args.parentId }),
          "operate_project_resource create parent"
        );
      }
      const nodeType = resolveNodeType(args.nodeKind);
      const created = bridge.createNodeFlowNode({
        expectedRevision,
        type: nodeType,
        nodeRef: defaultNodeRef(args),
        title: defaultTitle(args),
        text: args.nodeKind === "text" || args.nodeKind === "script" || args.nodeKind === "archive"
          ? args.text || args.content
          : undefined,
        content: args.content,
        documentId: args.nodeKind === "archive" || args.nodeKind === "script" ? defaultDocumentId(args) : undefined,
        imageUrl: args.nodeKind === "image" ? args.imageUrl : undefined,
        audioUrl: args.nodeKind === "audio" ? args.audioUrl : undefined,
        videoUrl: args.nodeKind === "video" ? args.videoUrl : undefined,
        pdfUrl: args.nodeKind === "pdf" ? args.pdfUrl : undefined,
        filename: args.filename,
        mimeType: args.mimeType,
        x: args.x,
        y: args.y,
        parentId: args.parentId,
      });
      return {
        layer: "nodeflow",
        entity: "node",
        target: "nodeflow:node",
        action: "create",
        updated: true,
        artifact: {
          kind: "node",
          target: "nodeflow:node",
          id: created.nodeId,
          ref: created.nodeRef || defaultNodeRef(args),
          title: created.title,
          node_kind: args.nodeKind,
        },
        item: {
          node_kind: args.nodeKind,
          node_id: created.nodeId,
          node_ref: created.nodeRef || defaultNodeRef(args),
          title: created.title,
        },
      };
    }

    if (args.entity === "node" && args.action === "update") {
      assertGenericWriteAllowedForNode(
        findNodeByIdOrRef(workflow, { nodeId: args.nodeId, nodeRef: args.nodeRef }),
        "operate_project_resource update"
      );
      const updated = bridge.updateNodeFlowNode({
        expectedRevision,
        nodeId: args.nodeId,
        nodeRef: args.nodeRef,
        patch: args.patch,
      });
      return {
        layer: "nodeflow",
        entity: "node",
        target: "nodeflow:node",
        action: "update",
        updated: true,
        review_required: updated.reviewRequired === true,
        commit_status: updated.commitStatus || "committed",
        artifact: {
          kind: "node",
          target: "nodeflow:node",
          id: updated.nodeId,
          ref: updated.nodeRef,
          title: updated.title,
          node_kind: updated.nodeType,
          review_required: updated.reviewRequired === true,
          commit_status: updated.commitStatus || "committed",
        },
        item: {
          node_id: updated.nodeId,
          node_ref: updated.nodeRef,
          node_kind: updated.nodeType,
          title: updated.title,
          patch: updated.patch,
          review_required: updated.reviewRequired === true,
          commit_status: updated.commitStatus || "committed",
        },
      };
    }

    if (args.entity === "node" && args.action === "move") {
      assertGenericWriteAllowedForNode(
        findNodeByIdOrRef(workflow, { nodeId: args.nodeId, nodeRef: args.nodeRef }),
        "operate_project_resource move"
      );
      const moved = bridge.moveNodeFlowNode({
        expectedRevision,
        nodeId: args.nodeId,
        nodeRef: args.nodeRef,
        x: args.x,
        y: args.y,
      });
      return {
        layer: "nodeflow",
        entity: "node",
        target: "nodeflow:node",
        action: "move",
        updated: true,
        artifact: {
          kind: "node",
          target: "nodeflow:node",
          id: moved.nodeId,
          ref: moved.nodeRef,
          title: moved.title,
          node_kind: moved.nodeType,
        },
        item: {
          node_id: moved.nodeId,
          node_ref: moved.nodeRef,
          node_kind: moved.nodeType,
          title: moved.title,
          position: moved.position,
        },
      };
    }

    if (args.entity === "link" && args.action === "connect" && args.linkKind === "canvas") {
      assertGenericWriteAllowedForNode(
        findNodeByIdOrRef(workflow, { nodeId: args.sourceNodeId, nodeRef: args.sourceRef }),
        "operate_project_resource connect source"
      );
      assertGenericWriteAllowedForNode(
        findNodeByIdOrRef(workflow, { nodeId: args.targetNodeId, nodeRef: args.targetRef }),
        "operate_project_resource connect target"
      );
      const connected = bridge.connectNodeFlowNodes({
        expectedRevision,
        sourceNodeId: args.sourceNodeId,
        targetNodeId: args.targetNodeId,
        sourceRef: args.sourceRef,
        targetRef: args.targetRef,
        sourceHandle: args.sourceHandle as NodeFlowHandle | undefined,
        targetHandle: args.targetHandle as NodeFlowHandle | undefined,
      });
      return {
        layer: "nodeflow",
        entity: "link",
        target: "nodeflow:link",
        action: "connect",
        updated: true,
        role: "connection",
        artifact: {
          kind: "link",
          target: "nodeflow:link",
          id: connected.linkId,
          title: "connection",
          source: {
            node_id: connected.sourceNodeId,
            node_ref: connected.sourceRef,
            handle: connected.sourceHandle,
          },
          destination: {
            node_id: connected.targetNodeId,
            node_ref: connected.targetRef,
            handle: connected.targetHandle,
          },
        },
        item: {
          link_id: connected.linkId,
          source_node_id: connected.sourceNodeId,
          target_node_id: connected.targetNodeId,
          source_ref: connected.sourceRef,
          target_ref: connected.targetRef,
          source_handle: connected.sourceHandle,
          target_handle: connected.targetHandle,
        },
      };
    }

    if (args.entity === "link" && args.action === "connect" && args.linkKind === "graph") {
      const sourceRef = resolveNodeFlowRefForGraph(workflow, args.sourceNodeId, args.sourceRef);
      const targetRef = resolveNodeFlowRefForGraph(workflow, args.targetNodeId, args.targetRef);
      if (!sourceRef || !targetRef) {
        throw new Error("创建 Flow 引用关系需要可解析的 source_ref 和 target_ref。");
      }
      assertGenericWriteAllowedForNode(
        findNodeByIdOrRef(workflow, { nodeId: args.sourceNodeId, nodeRef: sourceRef }),
        "operate_project_resource reference source"
      );
      assertGenericWriteAllowedForNode(
        findNodeByIdOrRef(workflow, { nodeId: args.targetNodeId, nodeRef: targetRef }),
        "operate_project_resource reference target"
      );
      const created = bridge.createNodeFlowGraphLink({
        expectedRevision,
        sourceRef,
        targetRef,
      });
      return {
        layer: "nodeflow",
        entity: "link",
        target: "nodeflow:link",
        action: "connect",
        updated: true,
        role: "reference",
        artifact: {
          kind: "link",
          target: "nodeflow:link",
          id: created.linkId,
          title: "reference",
          source: {
            node_ref: created.sourceRef,
          },
          destination: {
            node_ref: created.targetRef,
          },
        },
        item: {
          link_id: created.linkId,
          source_ref: created.sourceRef,
          target_ref: created.targetRef,
        },
      };
    }

    throw new Error(`operate_project_resource 不支持 action=${args.action}`);
  },
  summarize: (output: any) => {
    if (output?.entity === "node" && output?.action === "create") {
      return `创建 Flow 节点 ${output?.item?.title || output?.item?.node_ref || output?.item?.node_id}`;
    }
    if (output?.entity === "node" && output?.action === "update") {
      return output?.commit_status === "pending_review"
        ? `提交 Flow 节点 ${output?.item?.title || output?.item?.node_ref || output?.item?.node_id} 修改待审核`
        : `更新 Flow 节点 ${output?.item?.title || output?.item?.node_ref || output?.item?.node_id}`;
    }
    if (output?.entity === "node" && output?.action === "move") {
      return `移动 Flow 节点 ${output?.item?.title || output?.item?.node_ref || output?.item?.node_id}`;
    }
    if (output?.entity === "link" && output?.action === "connect") {
      return `连接 Flow ${output?.role === "reference" ? "引用关系" : "连接关系"} ${output?.item?.link_id || ""}`.trim();
    }
    return "更新 Flow 资源";
  },
};
