/* eslint-disable */
// Generated by scripts/generate-skill-manifest.mjs
import type { QalamResolvedSkill, QalamSkillManifest } from "./types";

type SkillRegistryEntry = {
  manifest: QalamSkillManifest;
  resolve: () => Promise<QalamResolvedSkill>;
};

const SKILL_REGISTRY: Record<string, SkillRegistryEntry> = {
  "design-taste-frontend": {
    manifest: {
      id: "design-taste-frontend",
      title: "High-Agency Frontend Skill",
      description: "Senior UI/UX engineer overlay for layout, visual direction, and interface refinement work.",
      sourcePath: ".agents/skills/design-taste-frontend/SKILL.md",
      activationMode: "explicit" as const,
      tags: ["frontend","ui","design"],
      preferredTools: [],
      disabledTools: [],
      implicitInvocationHints: ["frontend","界面","布局","视觉设计","UI polish"],
    },
    resolve: async () => {
      const mod = await import("./skillPackages/designTasteFrontend");
      return mod["resolveDesignTasteFrontendSkill"](SKILL_REGISTRY["design-taste-frontend"].manifest);
    },
  }
};

export const GENERATED_SKILL_MANIFESTS: QalamSkillManifest[] = Object.values(SKILL_REGISTRY).map((entry) => entry.manifest);

export const resolveGeneratedSkill = async (id: string): Promise<QalamResolvedSkill | null> => {
  const entry = SKILL_REGISTRY[id];
  if (!entry) return null;
  return entry.resolve();
};
